### ISSUE TITLE
Additional resources

### ISSUE THREAD

**Issue by dkt201474** [adrai/cqrs-sample#27]
Hi @adrai ,
I want to ask what resources (books, blogs, articles, videos...) do you recommend if I want to design a complex architecture based on your modules. (For example how to create bounded context, relationship between them, ...)

I read the documentation of your modules and have a good understanding of microservices, CQRS, ES, but I still have a lot of questions and I want to get it right.

I will really appreciate you input in this. 
Thank you in advance.

**Comment by adrai** [comment]
I have to be honest...
I’ve NEVER read a book about CQRS, ES or DDD...

Since I started with this topic several years ago there was not so much to read about it...
I have just read a couple of posts i.e. https://github.com/adrai/cqrs-sample/blob/master/README.md#why-should-i-care

The rest was learning by try&error...

But I have to admit: Designing an appropriate architecture based on CQRS / ES and make sure “it works” is hard... but the most difficult part is DDD.
Designing the “real” domain is crucial. You need to be the expert of your business domain or at least have the experts near you. (and this has nothing to do with programming)

**Comment by dkt201474** [comment]
Thank you.
